name: Test+Lint
on:
  pull_request:
jobs:
  test_and_lint:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: yarn install
      - name: Build packages
        run: yarn workspace @snort/nostr build
      - name: Run tests
        run: yarn workspace @snort/app test
      - name: Check Eslint
        run: yarn workspace @snort/app eslint
      - name: Check Formatting
        run: yarn workspace @snort/app prettier --check .
